# /opt/docker-compose.yml
---
version: '2'
services:
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    volumes:
      - /opt/appdata/sabnzbd:/config
      - /mnt/media:/media
    ports:
      - 8080:8080
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    volumes:
      - /opt/appdata/deluge:/config
      - /mnt/media:/downloads
    ports:
      - 8112:8112
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    depends_on:
      - sabnzbd
    volumes:
      - /opt/appdata/sonarr:/config
      - /mnt/media:/media
    ports:
      - 8989:8989
    links:
      - sabnzbd
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    depends_on:
      - deluge
    volumes:
      - /opt/appdata/jackett:/config
    ports:
      - 9117:9117
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
    restart:
      always
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    ports:
      - 443:443
    volumes:
      - /opt/appdata/letsencrypt/config:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
      - EMAIL=gregstengel@gmail.com
      - URL=gmachine.net
      - SUBDOMAINS=ferris
      - ONLY_SUBDOMAINS=true
    restart:
      always
  radarr:
      image: linuxserver/radarr
      container_name: radarr
      depends_on:
        - sabnzbd
      volumes:
        - /opt/appdata/radarr:/config
        - /mnt/media:/media
      ports:
        - 7878:7878
      links:
        - sabnzbd
      restart: always
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=America/New_York
  portainer:
      image: portainer/portainer
      container_name: portainer
      ports:
        - 9000:9000
      volumes:
        - /opt/appdata/portainer:/data
        - /var/run/docker.sock:/var/run/docker.sock
      restart:
        always
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=America/New_York
